Keras and the XOR Function

The XOR function is a well-known function that is not linear separable in the plane. The truth table for the XOR (“exclusive OR”) function is straightforward: given two binary inputs, the output is 1 if at most one input is a 1; otherwise, the output is 0. If we treat XOR as the name of a function with two binary inputs, here are the outputs:


XOR(0,0) = 0
XOR(1,0) = 1
XOR(0,1) = 1
XOR(1,1) = 0
We can treat the output values as labels that are associated with the input values. Specifically, the points (0,0) and (1,1) are in class 0 and the points (1,0) and (0,1) are in class 1. Draw these points in the plane, and you will have the four vertices of a unit square whose lower-left vertex is the origin. Moreover, each pair of diagonal elements belongs to the same class, and you cannot separate the points in class 0 from the points in class 1 with a straight line in the Euclidean plane. Hence, the XOR function is not linearly separable in the plane. If you're skeptical, try to find a linear separator for the XOR function in the Euclidean plane.



In [2]:
import tensorflow as tf
import numpy as np

In [36]:
#Logical XOR and truth values:

x = np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = np.array([[0.],[1.],[1.],[0.],])

In [5]:
x,y

(array([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]),
 array([[0.],
        [1.],
        [1.],
        [0.]]))

In [33]:
model = tf.keras.models.Sequential()

#2 inputs to the NN, 2 neuraons in the Hidden layer
model.add(tf.keras.layers.Dense(2, input_dim = 2, activation = 'relu'))

#2nd Hidden layer with 20 neurons
model.add(tf.keras.layers.Dense(20,activation = 'relu'))

#1 output to the NN
model.add(tf.keras.layers.Dense(1))



In [34]:
print("Compiling model....")
model.compile(loss= 'mean_squared_error', optimizer = 'adam')
print("Fitting model...")
model.fit(x,y, verbose = 0, epochs = 1000)
pred = model.predict(x)

Compiling model....
Fitting model...


In [35]:
# Test final prediction

print("Testing XOR operator")
p1 = np.array([[0.,0.]])
p2 = np.array([[0.,1.]])
p3 = np.array([[1.,0.]])
p4 = np.array([[1.,1.]])

print(p1, " : " ,model.predict(p1))
print(p2, " : " ,model.predict(p2))
print(p3, " : " ,model.predict(p3))
print(p4, " : " ,model.predict(p4))


Testing XOR operator
[[0. 0.]]  :  [[0.14652456]]
[[0. 1.]]  :  [[0.9353238]]
[[1. 0.]]  :  [[0.93534374]]
[[1. 1.]]  :  [[0.04654091]]


Activity - Try to improve the model chaging number of epochs

Activity - Can you try predict values and print it for NAND Logic gates